name: Run Cucumber Maven Tests

on:
  schedule:
    - cron: '0 23 * * *'  # Daily at 11 PM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and run tests
        run: mvn clean verify

      - name: Prepare report folder
        id: prep
        run: |
          REPORT_FOLDER=report-$(date -u +'%Y%m%dT%H%M%SZ')
          echo "report_folder=$REPORT_FOLDER" >> $GITHUB_OUTPUT

      - name: Copy report to index.html
        run: |
          REPORT_PATH="api/target/cucumber-reports/cucumber-html-reports"
          if [ -f "$REPORT_PATH/overview-features.html" ]; then
            cp "$REPORT_PATH/overview-features.html" "$REPORT_PATH/index.html"
          else
            echo "⚠️ Report not found: $REPORT_PATH/overview-features.html"
            exit 1
          fi

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: api/target/cucumber-reports/cucumber-html-reports/

      - name: Add link to GitHub summary
        run: |
          echo "📦 [Download Cucumber HTML Report Artifact](./artifacts/cucumber-html-report/index.html)" >> $GITHUB_STEP_SUMMARY

      - name: Send Slack notification (scheduled runs only)
        if: github.event_name == 'schedule'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          STATUS: ${{ job.status }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          if [ "$STATUS" = "success" ]; then
            ICON="✅"
            COLOR="#2eb886"
          else
            ICON="❌"
            COLOR="#e01e5a"
          fi

          RUN_URL="https://github.com/$REPO/actions/runs/$RUN_ID"
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"attachments\": [
              {
                \"color\": \"$COLOR\",
                \"title\": \"$ICON Nightly Cucumber Run: $STATUS\",
                \"title_link\": \"$RUN_URL\",
                \"fields\": [
                  {
                    \"title\": \"Repository\",
                    \"value\": \"$REPO\",
                    \"short\": true
                  },
                  {
                    \"title\": \"Timestamp\",
                    \"value\": \"$TIMESTAMP\",
                    \"short\": true
                  }
                ],
                \"footer\": \"GitHub Actions\",
                \"ts\": $(date +%s)
              }
            ]
          }" $SLACK_WEBHOOK_URL